// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: slime_boot.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	v1 "k8s.io/api/core/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SlimeBootStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlimeBootStatus) Reset()         { *m = SlimeBootStatus{} }
func (m *SlimeBootStatus) String() string { return proto.CompactTextString(m) }
func (*SlimeBootStatus) ProtoMessage()    {}
func (*SlimeBootStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf8433223eb5dea, []int{0}
}
func (m *SlimeBootStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlimeBootStatus.Unmarshal(m, b)
}
func (m *SlimeBootStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlimeBootStatus.Marshal(b, m, deterministic)
}
func (m *SlimeBootStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlimeBootStatus.Merge(m, src)
}
func (m *SlimeBootStatus) XXX_Size() int {
	return xxx_messageInfo_SlimeBootStatus.Size(m)
}
func (m *SlimeBootStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SlimeBootStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SlimeBootStatus proto.InternalMessageInfo

type SlimeBootSpec struct {
	Module         []*Config  `protobuf:"bytes,1,rep,name=module,proto3" json:"module,omitempty"`
	Component      *Component `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	Namespace      string     `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	IstioNamespace string     `protobuf:"bytes,4,opt,name=istioNamespace,proto3" json:"istioNamespace,omitempty"`
	// workload config
	ReplicaCount             int32                      `protobuf:"varint,5,opt,name=replicaCount,proto3" json:"replicaCount,omitempty"`
	Image                    *Image                     `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	PodSecurityContext       *v1.PodSecurityContext     `protobuf:"bytes,7,opt,name=podSecurityContext,proto3" json:"podSecurityContext,omitempty"`
	ContainerSecurityContext *v1.SecurityContext        `protobuf:"bytes,8,opt,name=containerSecurityContext,proto3" json:"containerSecurityContext,omitempty"`
	Resources                *v1.ResourceRequirements   `protobuf:"bytes,9,opt,name=resources,proto3" json:"resources,omitempty"`
	NodeSelector             map[string]string          `protobuf:"bytes,10,rep,name=nodeSelector,proto3" json:"nodeSelector,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Tolerations              []*v1.Toleration           `protobuf:"bytes,11,rep,name=tolerations,proto3" json:"tolerations,omitempty"`
	Affinity                 *v1.Affinity               `protobuf:"bytes,12,opt,name=affinity,proto3" json:"affinity,omitempty"`
	Volumes                  []*v1.Volume               `protobuf:"bytes,13,rep,name=volumes,proto3" json:"volumes,omitempty"`
	VolumeMounts             []*v1.VolumeMount          `protobuf:"bytes,14,rep,name=volumeMounts,proto3" json:"volumeMounts,omitempty"`
	ImagePullSecrets         []*v1.LocalObjectReference `protobuf:"bytes,15,rep,name=imagePullSecrets,proto3" json:"imagePullSecrets,omitempty"`
	Service                  *Service                   `protobuf:"bytes,16,opt,name=service,proto3" json:"service,omitempty"`
	ServiceAccount           *ServiceAccount            `protobuf:"bytes,17,opt,name=serviceAccount,proto3" json:"serviceAccount,omitempty"`
	Args                     []string                   `protobuf:"bytes,18,rep,name=args,proto3" json:"args,omitempty"`
	Env                      []*v1.EnvVar               `protobuf:"bytes,19,rep,name=env,proto3" json:"env,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                   `json:"-"`
	XXX_unrecognized         []byte                     `json:"-"`
	XXX_sizecache            int32                      `json:"-"`
}

func (m *SlimeBootSpec) Reset()         { *m = SlimeBootSpec{} }
func (m *SlimeBootSpec) String() string { return proto.CompactTextString(m) }
func (*SlimeBootSpec) ProtoMessage()    {}
func (*SlimeBootSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf8433223eb5dea, []int{1}
}
func (m *SlimeBootSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlimeBootSpec.Unmarshal(m, b)
}
func (m *SlimeBootSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlimeBootSpec.Marshal(b, m, deterministic)
}
func (m *SlimeBootSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlimeBootSpec.Merge(m, src)
}
func (m *SlimeBootSpec) XXX_Size() int {
	return xxx_messageInfo_SlimeBootSpec.Size(m)
}
func (m *SlimeBootSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_SlimeBootSpec.DiscardUnknown(m)
}

var xxx_messageInfo_SlimeBootSpec proto.InternalMessageInfo

func (m *SlimeBootSpec) GetModule() []*Config {
	if m != nil {
		return m.Module
	}
	return nil
}

func (m *SlimeBootSpec) GetComponent() *Component {
	if m != nil {
		return m.Component
	}
	return nil
}

func (m *SlimeBootSpec) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SlimeBootSpec) GetIstioNamespace() string {
	if m != nil {
		return m.IstioNamespace
	}
	return ""
}

func (m *SlimeBootSpec) GetReplicaCount() int32 {
	if m != nil {
		return m.ReplicaCount
	}
	return 0
}

func (m *SlimeBootSpec) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *SlimeBootSpec) GetPodSecurityContext() *v1.PodSecurityContext {
	if m != nil {
		return m.PodSecurityContext
	}
	return nil
}

func (m *SlimeBootSpec) GetContainerSecurityContext() *v1.SecurityContext {
	if m != nil {
		return m.ContainerSecurityContext
	}
	return nil
}

func (m *SlimeBootSpec) GetResources() *v1.ResourceRequirements {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *SlimeBootSpec) GetNodeSelector() map[string]string {
	if m != nil {
		return m.NodeSelector
	}
	return nil
}

func (m *SlimeBootSpec) GetTolerations() []*v1.Toleration {
	if m != nil {
		return m.Tolerations
	}
	return nil
}

func (m *SlimeBootSpec) GetAffinity() *v1.Affinity {
	if m != nil {
		return m.Affinity
	}
	return nil
}

func (m *SlimeBootSpec) GetVolumes() []*v1.Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *SlimeBootSpec) GetVolumeMounts() []*v1.VolumeMount {
	if m != nil {
		return m.VolumeMounts
	}
	return nil
}

func (m *SlimeBootSpec) GetImagePullSecrets() []*v1.LocalObjectReference {
	if m != nil {
		return m.ImagePullSecrets
	}
	return nil
}

func (m *SlimeBootSpec) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *SlimeBootSpec) GetServiceAccount() *ServiceAccount {
	if m != nil {
		return m.ServiceAccount
	}
	return nil
}

func (m *SlimeBootSpec) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *SlimeBootSpec) GetEnv() []*v1.EnvVar {
	if m != nil {
		return m.Env
	}
	return nil
}

type ServiceAccount struct {
	Create               bool     `protobuf:"varint,1,opt,name=create,proto3" json:"create,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceAccount) Reset()         { *m = ServiceAccount{} }
func (m *ServiceAccount) String() string { return proto.CompactTextString(m) }
func (*ServiceAccount) ProtoMessage()    {}
func (*ServiceAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf8433223eb5dea, []int{2}
}
func (m *ServiceAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceAccount.Unmarshal(m, b)
}
func (m *ServiceAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceAccount.Marshal(b, m, deterministic)
}
func (m *ServiceAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceAccount.Merge(m, src)
}
func (m *ServiceAccount) XXX_Size() int {
	return xxx_messageInfo_ServiceAccount.Size(m)
}
func (m *ServiceAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceAccount.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceAccount proto.InternalMessageInfo

func (m *ServiceAccount) GetCreate() bool {
	if m != nil {
		return m.Create
	}
	return false
}

type Component struct {
	GlobalSidecarNamespace []string       `protobuf:"bytes,1,rep,name=globalSidecarNamespace,proto3" json:"globalSidecarNamespace,omitempty"`
	ReportServer           bool           `protobuf:"varint,2,opt,name=reportServer,proto3" json:"reportServer,omitempty"`
	GlobalSidecar          *GlobalSidecar `protobuf:"bytes,3,opt,name=globalSidecar,proto3" json:"globalSidecar,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}       `json:"-"`
	XXX_unrecognized       []byte         `json:"-"`
	XXX_sizecache          int32          `json:"-"`
}

func (m *Component) Reset()         { *m = Component{} }
func (m *Component) String() string { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()    {}
func (*Component) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf8433223eb5dea, []int{3}
}
func (m *Component) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component.Unmarshal(m, b)
}
func (m *Component) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component.Marshal(b, m, deterministic)
}
func (m *Component) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component.Merge(m, src)
}
func (m *Component) XXX_Size() int {
	return xxx_messageInfo_Component.Size(m)
}
func (m *Component) XXX_DiscardUnknown() {
	xxx_messageInfo_Component.DiscardUnknown(m)
}

var xxx_messageInfo_Component proto.InternalMessageInfo

func (m *Component) GetGlobalSidecarNamespace() []string {
	if m != nil {
		return m.GlobalSidecarNamespace
	}
	return nil
}

func (m *Component) GetReportServer() bool {
	if m != nil {
		return m.ReportServer
	}
	return false
}

func (m *Component) GetGlobalSidecar() *GlobalSidecar {
	if m != nil {
		return m.GlobalSidecar
	}
	return nil
}

type Image struct {
	Repository           string   `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	PullPolicy           string   `protobuf:"bytes,3,opt,name=pullPolicy,proto3" json:"pullPolicy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf8433223eb5dea, []int{4}
}
func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *Image) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Image) GetPullPolicy() string {
	if m != nil {
		return m.PullPolicy
	}
	return ""
}

type Service struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	AuxiliaryPort        int32    `protobuf:"varint,3,opt,name=auxiliaryPort,proto3" json:"auxiliaryPort,omitempty"`
	LogSourcePort        int32    `protobuf:"varint,4,opt,name=logSourcePort,proto3" json:"logSourcePort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf8433223eb5dea, []int{5}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Service) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Service) GetAuxiliaryPort() int32 {
	if m != nil {
		return m.AuxiliaryPort
	}
	return 0
}

func (m *Service) GetLogSourcePort() int32 {
	if m != nil {
		return m.LogSourcePort
	}
	return 0
}

type GlobalSidecar struct {
	Enable               bool                         `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	Port                 int32                        `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	ProbePort            int32                        `protobuf:"varint,3,opt,name=probePort,proto3" json:"probePort,omitempty"`
	Replicas             int32                        `protobuf:"varint,4,opt,name=replicas,proto3" json:"replicas,omitempty"`
	SidecarInject        *GlobalSidecar_SidecarInject `protobuf:"bytes,5,opt,name=sidecarInject,proto3" json:"sidecarInject,omitempty"`
	Image                *Image                       `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Resources            *v1.ResourceRequirements     `protobuf:"bytes,7,opt,name=resources,proto3" json:"resources,omitempty"`
	LegacyFilterName     string                       `protobuf:"bytes,8,opt,name=legacyFilterName,proto3" json:"legacyFilterName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GlobalSidecar) Reset()         { *m = GlobalSidecar{} }
func (m *GlobalSidecar) String() string { return proto.CompactTextString(m) }
func (*GlobalSidecar) ProtoMessage()    {}
func (*GlobalSidecar) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf8433223eb5dea, []int{6}
}
func (m *GlobalSidecar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalSidecar.Unmarshal(m, b)
}
func (m *GlobalSidecar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalSidecar.Marshal(b, m, deterministic)
}
func (m *GlobalSidecar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalSidecar.Merge(m, src)
}
func (m *GlobalSidecar) XXX_Size() int {
	return xxx_messageInfo_GlobalSidecar.Size(m)
}
func (m *GlobalSidecar) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalSidecar.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalSidecar proto.InternalMessageInfo

func (m *GlobalSidecar) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *GlobalSidecar) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *GlobalSidecar) GetProbePort() int32 {
	if m != nil {
		return m.ProbePort
	}
	return 0
}

func (m *GlobalSidecar) GetReplicas() int32 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func (m *GlobalSidecar) GetSidecarInject() *GlobalSidecar_SidecarInject {
	if m != nil {
		return m.SidecarInject
	}
	return nil
}

func (m *GlobalSidecar) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *GlobalSidecar) GetResources() *v1.ResourceRequirements {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *GlobalSidecar) GetLegacyFilterName() string {
	if m != nil {
		return m.LegacyFilterName
	}
	return ""
}

type GlobalSidecar_SidecarInject struct {
	Enable               bool              `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	Mode                 string            `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Annotations          map[string]string `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Labels               map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GlobalSidecar_SidecarInject) Reset()         { *m = GlobalSidecar_SidecarInject{} }
func (m *GlobalSidecar_SidecarInject) String() string { return proto.CompactTextString(m) }
func (*GlobalSidecar_SidecarInject) ProtoMessage()    {}
func (*GlobalSidecar_SidecarInject) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf8433223eb5dea, []int{6, 0}
}
func (m *GlobalSidecar_SidecarInject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalSidecar_SidecarInject.Unmarshal(m, b)
}
func (m *GlobalSidecar_SidecarInject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalSidecar_SidecarInject.Marshal(b, m, deterministic)
}
func (m *GlobalSidecar_SidecarInject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalSidecar_SidecarInject.Merge(m, src)
}
func (m *GlobalSidecar_SidecarInject) XXX_Size() int {
	return xxx_messageInfo_GlobalSidecar_SidecarInject.Size(m)
}
func (m *GlobalSidecar_SidecarInject) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalSidecar_SidecarInject.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalSidecar_SidecarInject proto.InternalMessageInfo

func (m *GlobalSidecar_SidecarInject) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *GlobalSidecar_SidecarInject) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *GlobalSidecar_SidecarInject) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *GlobalSidecar_SidecarInject) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func init() {
	proto.RegisterType((*SlimeBootStatus)(nil), "slime.config.v1alpha1.SlimeBootStatus")
	proto.RegisterType((*SlimeBootSpec)(nil), "slime.config.v1alpha1.SlimeBootSpec")
	proto.RegisterMapType((map[string]string)(nil), "slime.config.v1alpha1.SlimeBootSpec.NodeSelectorEntry")
	proto.RegisterType((*ServiceAccount)(nil), "slime.config.v1alpha1.ServiceAccount")
	proto.RegisterType((*Component)(nil), "slime.config.v1alpha1.Component")
	proto.RegisterType((*Image)(nil), "slime.config.v1alpha1.Image")
	proto.RegisterType((*Service)(nil), "slime.config.v1alpha1.Service")
	proto.RegisterType((*GlobalSidecar)(nil), "slime.config.v1alpha1.GlobalSidecar")
	proto.RegisterType((*GlobalSidecar_SidecarInject)(nil), "slime.config.v1alpha1.GlobalSidecar.SidecarInject")
	proto.RegisterMapType((map[string]string)(nil), "slime.config.v1alpha1.GlobalSidecar.SidecarInject.AnnotationsEntry")
	proto.RegisterMapType((map[string]string)(nil), "slime.config.v1alpha1.GlobalSidecar.SidecarInject.LabelsEntry")
}

func init() { proto.RegisterFile("slime_boot.proto", fileDescriptor_6bf8433223eb5dea) }

var fileDescriptor_6bf8433223eb5dea = []byte{
	// 987 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0x97, 0xe3, 0x38, 0xc9, 0x8d, 0xe3, 0xd4, 0x59, 0xa0, 0x3a, 0x59, 0x21, 0x58, 0xa6, 0x54,
	0x16, 0x82, 0xb3, 0x62, 0xa0, 0x0a, 0x3c, 0x04, 0xd2, 0xa8, 0x45, 0x45, 0x6d, 0x89, 0xd6, 0x55,
	0x04, 0x7d, 0xa9, 0xd6, 0xeb, 0xb1, 0x59, 0xb2, 0xde, 0x3d, 0xf6, 0xf6, 0x4c, 0xfd, 0xc0, 0xa7,
	0xe2, 0xdb, 0xf0, 0x25, 0x78, 0xe2, 0x1d, 0xed, 0xde, 0xf9, 0xcf, 0x39, 0x76, 0xd5, 0xe4, 0x6d,
	0x76, 0xee, 0xf7, 0xfb, 0xcd, 0xee, 0xcc, 0xec, 0xec, 0x41, 0x3d, 0x91, 0x62, 0x8c, 0x6f, 0xfa,
	0x5a, 0xdb, 0x28, 0x36, 0xda, 0x6a, 0xf2, 0x91, 0xf7, 0x44, 0x5c, 0xab, 0xa1, 0x18, 0x45, 0x93,
	0x13, 0x26, 0xe3, 0xdf, 0xd8, 0x49, 0x63, 0x3f, 0x77, 0x78, 0x50, 0xa3, 0x75, 0x7d, 0x9a, 0x44,
	0x42, 0x77, 0x58, 0x2c, 0x3a, 0x5c, 0x1b, 0xec, 0x4c, 0x4e, 0x3a, 0x23, 0x54, 0x68, 0x98, 0xc5,
	0x41, 0x86, 0x69, 0x1d, 0xc2, 0xbd, 0x9e, 0x93, 0x7a, 0xac, 0xb5, 0xed, 0x59, 0x66, 0xd3, 0xa4,
	0xf5, 0x4f, 0x00, 0xb5, 0x85, 0x2f, 0x46, 0x4e, 0xbe, 0x81, 0x9d, 0xb1, 0x1e, 0xa4, 0x12, 0xc3,
	0x52, 0xb3, 0xdc, 0xae, 0x76, 0x3f, 0x8e, 0xd6, 0x86, 0x8f, 0x2e, 0xfc, 0x9a, 0xe6, 0x60, 0x72,
	0x06, 0x01, 0xd7, 0xe3, 0x58, 0x2b, 0x54, 0x36, 0xdc, 0x6a, 0x96, 0xda, 0xd5, 0x6e, 0x73, 0x23,
	0x33, 0xc7, 0xd1, 0x05, 0x85, 0x1c, 0x41, 0xa0, 0xd8, 0x18, 0x93, 0x98, 0x71, 0x0c, 0xcb, 0xcd,
	0x52, 0x3b, 0xa0, 0x0b, 0x07, 0x79, 0x08, 0x07, 0x22, 0xb1, 0x42, 0xbf, 0x9c, 0x43, 0xb6, 0x3d,
	0x64, 0xc5, 0x4b, 0x5a, 0xb0, 0x6f, 0x30, 0x96, 0x82, 0xb3, 0x0b, 0x9d, 0x2a, 0x1b, 0x56, 0x9a,
	0xa5, 0x76, 0x85, 0x16, 0x7c, 0xa4, 0x0b, 0x15, 0x31, 0x66, 0x23, 0x0c, 0x77, 0xfc, 0x2e, 0x8f,
	0x36, 0xec, 0xf2, 0x99, 0xc3, 0xd0, 0x0c, 0x4a, 0xae, 0x80, 0xc4, 0x7a, 0xd0, 0x43, 0x9e, 0x1a,
	0x61, 0xa7, 0x17, 0x5a, 0x59, 0x7c, 0x6b, 0xc3, 0x5d, 0x2f, 0xf0, 0x30, 0xca, 0x52, 0x1f, 0xb1,
	0x58, 0x44, 0x2e, 0xf5, 0xd1, 0xe4, 0x24, 0xba, 0xbc, 0x81, 0xa6, 0x6b, 0x14, 0xc8, 0x1b, 0x08,
	0xb9, 0x56, 0x96, 0x09, 0x85, 0x66, 0x55, 0x7d, 0xcf, 0xab, 0x7f, 0xba, 0x4e, 0x7d, 0x55, 0x7a,
	0xa3, 0x08, 0x79, 0x0a, 0x81, 0xc1, 0x44, 0xa7, 0x86, 0x63, 0x12, 0x06, 0x5e, 0xb1, 0xbd, 0x4e,
	0x91, 0xe6, 0x20, 0x8a, 0x7f, 0xa4, 0xc2, 0xe0, 0x18, 0x95, 0x4d, 0xe8, 0x82, 0x4a, 0x5e, 0xc3,
	0xbe, 0xd2, 0x03, 0xec, 0xa1, 0x44, 0x6e, 0xb5, 0x09, 0xc1, 0xf7, 0xc6, 0xa3, 0x0d, 0xb9, 0x2b,
	0x74, 0x54, 0xf4, 0x72, 0x89, 0xf8, 0x44, 0x59, 0x33, 0xa5, 0x05, 0x2d, 0xf2, 0x03, 0x54, 0xad,
	0x96, 0xae, 0x53, 0x85, 0x56, 0x49, 0x58, 0xf5, 0xd2, 0xc7, 0xeb, 0x76, 0xf9, 0x6a, 0x0e, 0xa3,
	0xcb, 0x14, 0x72, 0x0a, 0x7b, 0x6c, 0x38, 0x14, 0x4a, 0xd8, 0x69, 0xb8, 0x9f, 0x57, 0x75, 0x0d,
	0xfd, 0x3c, 0xc7, 0xd0, 0x39, 0x9a, 0x7c, 0x0d, 0xbb, 0x13, 0x2d, 0xd3, 0x31, 0x26, 0x61, 0xcd,
	0xc7, 0x6d, 0xac, 0x23, 0x5e, 0x79, 0x08, 0x9d, 0x41, 0xc9, 0x05, 0xec, 0x67, 0xe6, 0x0b, 0xd7,
	0x51, 0x49, 0x78, 0xe0, 0xa9, 0x9f, 0x6c, 0xa6, 0x7a, 0x1c, 0x2d, 0x90, 0xc8, 0x2b, 0xa8, 0xfb,
	0xe6, 0xba, 0x4c, 0xa5, 0xec, 0x21, 0x37, 0x68, 0x93, 0xf0, 0x9e, 0x17, 0x5a, 0x5b, 0xa1, 0xe7,
	0x9a, 0x33, 0xf9, 0x73, 0xff, 0x77, 0xe4, 0x96, 0xe2, 0x10, 0x0d, 0x2a, 0x8e, 0xf4, 0x86, 0x02,
	0x39, 0x85, 0xdd, 0x04, 0xcd, 0x44, 0x70, 0x0c, 0xeb, 0x3e, 0x13, 0xc7, 0x9b, 0x6a, 0x94, 0xa1,
	0xe8, 0x0c, 0x4e, 0x5e, 0xc0, 0x41, 0x6e, 0x9e, 0x73, 0xee, 0x6f, 0xcf, 0xa1, 0x17, 0xf8, 0xec,
	0xdd, 0x02, 0x39, 0x98, 0xae, 0x90, 0x09, 0x81, 0x6d, 0x66, 0x46, 0x49, 0x48, 0x9a, 0xe5, 0x76,
	0x40, 0xbd, 0x4d, 0xbe, 0x80, 0x32, 0xaa, 0x49, 0xf8, 0xc1, 0xe6, 0x4c, 0x3f, 0x51, 0x93, 0x2b,
	0x66, 0xa8, 0x83, 0x35, 0xbe, 0x87, 0xc3, 0x1b, 0xad, 0x43, 0xea, 0x50, 0xbe, 0xc6, 0x69, 0x58,
	0xf2, 0xd7, 0xdf, 0x99, 0xe4, 0x43, 0xa8, 0x4c, 0x98, 0x4c, 0xd1, 0x4f, 0x9d, 0x80, 0x66, 0x8b,
	0xef, 0xb6, 0x4e, 0x4b, 0xad, 0x36, 0x1c, 0x14, 0x37, 0x49, 0xee, 0xc3, 0x0e, 0x37, 0xc8, 0x2c,
	0x7a, 0x81, 0x3d, 0x9a, 0xaf, 0x5a, 0x7f, 0x97, 0x20, 0x98, 0x8f, 0x25, 0xf2, 0x08, 0xee, 0x8f,
	0xa4, 0xee, 0x33, 0xd9, 0x13, 0x03, 0xe4, 0xcc, 0x2c, 0xa6, 0x4e, 0xc9, 0x1f, 0x66, 0xc3, 0xd7,
	0x7c, 0xfa, 0x68, 0x63, 0x5d, 0x54, 0x34, 0x7e, 0x43, 0x7b, 0xb4, 0xe0, 0x23, 0x3f, 0x41, 0xad,
	0xc0, 0xf6, 0xb3, 0xae, 0xda, 0x7d, 0xb0, 0x21, 0xc9, 0x3f, 0x2e, 0x63, 0x69, 0x91, 0xda, 0xfa,
	0x15, 0x2a, 0x7e, 0x4a, 0x91, 0x63, 0x00, 0x17, 0x24, 0x11, 0x56, 0x9b, 0x59, 0x6e, 0x96, 0x3c,
	0x2e, 0x69, 0x96, 0x8d, 0xf2, 0x04, 0x39, 0xd3, 0x31, 0xe2, 0x54, 0xca, 0x4b, 0x2d, 0x05, 0x9f,
	0xe6, 0xf3, 0x76, 0xc9, 0xd3, 0xfa, 0x0b, 0x76, 0xf3, 0xd4, 0xb9, 0x42, 0xda, 0x69, 0x8c, 0xb9,
	0xac, 0xb7, 0x9d, 0xcf, 0x9d, 0xc9, 0x2b, 0x56, 0xa8, 0xb7, 0xc9, 0x03, 0xa8, 0xb1, 0xf4, 0xad,
	0x90, 0x82, 0x99, 0xe9, 0xa5, 0xfb, 0x58, 0xf6, 0x1f, 0x8b, 0x4e, 0x87, 0x92, 0x7a, 0xd4, 0xf3,
	0x63, 0xc5, 0xa3, 0xb6, 0x33, 0x54, 0xc1, 0xd9, 0xfa, 0xb7, 0x02, 0xb5, 0xc2, 0xd1, 0x5d, 0xe5,
	0x50, 0xb1, 0xbe, 0x9c, 0x57, 0x2e, 0x5b, 0xad, 0xdd, 0xc9, 0x11, 0x04, 0xb1, 0xd1, 0x7d, 0x5c,
	0xda, 0xc5, 0xc2, 0x41, 0x1a, 0xb0, 0x97, 0xbf, 0x07, 0x49, 0x1e, 0x7c, 0xbe, 0x26, 0xbf, 0x40,
	0x2d, 0xc9, 0x02, 0x3e, 0x53, 0xee, 0xa6, 0xf9, 0x07, 0xa4, 0xda, 0xed, 0xbe, 0x4f, 0x75, 0xa2,
	0xde, 0x32, 0x93, 0x16, 0x85, 0xee, 0xf4, 0xea, 0x14, 0x86, 0xf7, 0xee, 0xdd, 0x87, 0xf7, 0xe7,
	0x50, 0x97, 0x38, 0x62, 0x7c, 0xfa, 0x54, 0x48, 0x8b, 0xbe, 0x61, 0xfd, 0xeb, 0x12, 0xd0, 0x1b,
	0xfe, 0xc6, 0x7f, 0x5b, 0x50, 0x2b, 0x1c, 0xe4, 0x5d, 0x99, 0x1f, 0xeb, 0xc1, 0xec, 0xda, 0x79,
	0x9b, 0x20, 0x54, 0x99, 0x52, 0xda, 0xe6, 0xa3, 0xbc, 0xec, 0x2f, 0xfa, 0xc5, 0xed, 0xb3, 0x17,
	0x9d, 0x2f, 0x54, 0xb2, 0x27, 0x63, 0x59, 0x97, 0x5c, 0xc1, 0x8e, 0x64, 0x7d, 0x94, 0xae, 0x80,
	0x2e, 0xc2, 0xd9, 0x1d, 0x22, 0x3c, 0xf7, 0x02, 0x99, 0x78, 0xae, 0xd6, 0x38, 0x83, 0xfa, 0x6a,
	0xe0, 0xdb, 0x0c, 0x9c, 0xc6, 0xb7, 0x50, 0x5d, 0x92, 0xbd, 0x0d, 0xf5, 0x71, 0xe7, 0xf5, 0x97,
	0xd9, 0x19, 0x84, 0xee, 0x78, 0xa3, 0x33, 0x34, 0x6c, 0x8c, 0x7f, 0x6a, 0x73, 0xed, 0xfe, 0xe9,
	0x92, 0x4e, 0x76, 0xb6, 0xce, 0xec, 0x6c, 0xfd, 0x1d, 0xff, 0x4f, 0xf7, 0xd5, 0xff, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x5f, 0x27, 0x8f, 0x36, 0x30, 0x0a, 0x00, 0x00,
}
